name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  record: ^5.2.1
  audioplayers: ^5.2.1
  flutter_lints: ^6.0.0
  sqflite: ^2.4.3
  sqflite_common_ffi_web: ^1.1.2
  path: ^1.9.1
  http: ^1.6.0
  super_clipboard: ^0.9.1
  web: 1.1.1

flutter:
  uses-material-design: true
